<a href="https://colab.research.google.com/github/Shigatsu82/colabgoogle/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# np.zeros()

* np.zeros adalah fungsi yang berguna ingin membuat dummy sebuah matriks
* Parameter pertama mengindikasin berapa banyak child array yang akan dibuat
* Jika memasukan 2 parameter maka akan menentukan jumlah index pada child array yang ada

In [5]:


b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.zeros([3, 3])
print("\nMatrix c : \n", c)

d = np.zeros([4, 4])
print("\nMatrix d: \n", d)


Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix d: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Operasi Aritmatika pada Array

In [7]:

a = np.array([8, 15, 30, 170])
b = np.array([2, 5, 10, 30])

answer = a+b
print(answer)

answer = np.add(a, b)
print(answer)

c = np.array([1, 2, 3, 4])
answer = a+b+c
print(answer)

answer = np.add(a, b, c)
print(answer)
#Saat menambahkan ketiga array dengan fungsi np.add(a,b,c) belum diketahui penyebab kenapa array c tidak ditambahkan bersama dengan a dan b

[ 10  20  40 200]
[ 10  20  40 200]
[ 11  22  43 204]
[ 10  20  40 200]
